### PR TITLE
fix #1030

### LINKED ISSUE #1030: headerTimeout/bodyTimeout have a bug with keep-alive
Keep-alive - mode, headerTimeout/bodyTimeout 60s by default timeout, it will lead to send 408 messages, and close the connection.

1. client send a request to pistache server with keep-alive
2. **server reply 200 OK**
3. wait 60s do nothing
4. now pistache will get the timeout connection, send 408 message and close the connection

endpoint.cc line near 122: 
```
// ......
            auto* step = parser->step();
            if (step->id() == Private::RequestLineStep::Id || step->id() == Private::HeadersStep::Id)
            {
                if (elapsed > headerTimeout_ || elapsed > bodyTimeout_)
                    idlePeers.push_back(peer);  // <---------------------------
            }
            else if (step->id() == Private::BodyStep::Id)
            {
                if (elapsed > bodyTimeout_)
                    idlePeers.push_back(peer);
            }
        }

        for (const auto& idlePeer : idlePeers)
        {
            ResponseWriter response(Http::Version::Http11, this, static_cast<Http::Handler*>(handler_.get()), idlePeer);
            response.send(Http::Code::Request_Timeout).then([=](ssize_t) { removePeer(idlePeer); }, [=](std::exception_ptr) { removePeer(idlePeer); });
        }
```

### PR DESCRIPTION
**Pull request by zydxhs**
1. Keep-alive connection server endpoint, send 408 message after idle timeout, it's not expected.
2. I add an keep-alive timeout option. Before starting the HTTP service, you can set the keepalive time for the long connection. If the keepalive time exceeds this value, you can disable the long connection.
3. I use tcpdump capture packet, confirming that 408 is not sent and the connection is directly closed.

### CODE REVIEW

**Comment by kiplingw** [comment]
This is to fix #1030. I'm not very familiar with this portion of the code base, but @dennisjenkins75 knows a lot more than I do about the network i/o logic. @dennisjenkins75, happy to merge if you're fine with it and pending CI passes.

**Review by kiplingw — APPROVED** [review]

**Comment by Tachi107** [comment]
A meaningful commit message would be appreciated, so that one doesn't have to open this pull request page to see why and what has changed

**Comment by kiplingw** [comment]
@zydxhs, please perform the following as soon as you are able:

* Rebase;
* Add a more descriptive commit log, as @Tachi107 suggested;
* Bump the version minor version [because you've added new interfaces](https://github.com/pistacheio/pistache#versioning) that (in theory) should not break old ones. While you are at it, also bump the date. You can do both of these in `version.txt`.

**Review by dennisjenkins75 — COMMENTED** [review]
I skimmed the code.

I'd like to see unit tests that prove correct behavior when:

1. keep-alive is enabled, but pistache times out.
2. keep-alive is enabled, but the client times out (**really important**).
3. keep-alive is disabled, the client fails to request it, the client behaves as if it were enabled, but pistache behaves as if it were disabled.
4. keep-alive is disabled, never requested, and pistache behaves as expected.

Some of these tests might be hard to do with a conformant HTTP client, like libcurl.  You might need to code a minimal raw TCP HTTP client in order to coerce the HTTP state.

Its really important to test a non-conformant client, otherwise a misbehaving, or malicious, client could DOS a pistache process by consuming the connections and then going idle.

**Comment by kiplingw** [comment]
I'm in agreement with my friend @dennisjenkins75. @zydxhs, also don't forget to rebase before you add your unit tests.

**Comment by zydxhs** [comment]
@dennisjenkins75, I have very little knowledge of HTTP protocol, and I don't know how to implement timeout.

**Comment by zydxhs** [comment]
> @zydxhs, please perform the following as soon as you are able:
> 
> * Rebase;
> * Add a more descriptive commit log, as @Tachi107 suggested;
> * Bump the version minor version [because you've added new interfaces](https://github.com/pistacheio/pistache#versioning) that (in theory) should not break old ones. While you are at it, also bump the date. You can do both of these in `version.txt`.

@kiplingw How can I change the descriptive commit log?

**Comment by kiplingw** [comment]
> @kiplingw How can I change the descriptive commit log?

You can do so via [this](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message).

**Comment by zydxhs** [comment]
Hi, I have added unit tests.

**Comment by Tachi107** [comment]
I haven't looked at the tests yet, but unfortunately your branch has merge conflicts. Could you please rebase onto the latest master branch?

**Comment by zydxhs** [comment]
I'm sorry. I've done the rebase Now.

**Comment by kiplingw** [comment]
Looks like we are getting CI failures:

```
Dependency gmock found: NO unknown version, but need: ['>=1.11.0']
```

@Tachi107, did I break something?

**Comment by Tachi107** [comment]
Ops, my fault. In the [patch] to disable the GMock requirement I forgot to also remove the GMock check from the meson.build files.

I'll fix it later today :)

[patch]: https://github.com/pistacheio/pistache/blob/debian/patches/disable-gmock-1.11-tests.patch

**Comment by zydxhs** [comment]
@kiplingw, @Tachi107 
When can this PR be merged?

**Comment by kiplingw** [comment]
@Tachi107 is going to make a minor change to the build environment and then we'll re-run your PR through CI. Please hang tight @zydxhs.

**Comment by Tachi107** [comment]
@zydxhs the autopkgtest job now runs correctly, but it seems that your commit for GCC 7 compatibility (https://github.com/pistacheio/pistache/pull/1061/commits/e0c3f0f840dea155d67439385aed6613a1d54736) is breaking stuff for newer toolchains - the build reports: "`error: reference to ‘filesystem’ is ambiguous`".

GCC 7 is more than five years old, do you really need to support it?

**Comment by kiplingw** [comment]
Complete C++17 support was added in GCC 8. I think it's totally reasonable to drop support for older compilers.

**Comment by zydxhs** [comment]
> @zydxhs the autopkgtest job now runs correctly, but it seems that your commit for GCC 7 compatibility ([e0c3f0f](https://github.com/pistacheio/pistache/commit/e0c3f0f840dea155d67439385aed6613a1d54736)) is breaking stuff for newer toolchains - the build reports: "`error: reference to ‘filesystem’ is ambiguous`".
> 
> GCC 7 is more than five years old, do you really need to support it?

Yes, I am currently using GCC 7.5.0 and will not be upgrading GCC for quite some time.

**Comment by zydxhs** [comment]
@dennisjenkins75 @Tachi107 I updated the code using namespace alias, please review it again.
```c++
#if __GNUG__ <= 7
#include <experimental/filesystem>
namespace filesystem = std::experimental::filesystem;
#else
#include <filesystem>
namespace filesystem = std::filesystem;
#endif
```

**Comment by kiplingw** [comment]
Thanks @zydxhs. Please bump the version in version.txt per the [instructions](https://github.com/pistacheio/pistache/#versioning) in our readme. Also do the same in `debian/changelog`. Once done, I will merge if all CI passes.

**Comment by zydxhs** [comment]
ok

**Review by kiplingw — CHANGES_REQUESTED** [review]
Don't forget `debian/changelog` too.

**Comment by Tachi107** [comment]
> Don't forget `debian/changelog` too.

It can't be changed in this PR, it is in another branch

**Comment by kiplingw** [comment]
@zydxhs, CI is failing on several architectures..

**Comment by zydxhs** [comment]
How to change debian/changelog ?

File: src/common/description.cc [hunk 1]
```diff
@@ -15,8 +15,14 @@
...
 #include <algorithm>
-#include <filesystem>
 #include <sstream>
+#if __GNUG__ <= 7
+#include <experimental/filesystem>
+namespace filesystem = std::experimental::filesystem;
+#else
+#include <filesystem>
+namespace filesystem = std::filesystem;
+#endif
```
Comment (Tachi107) [inline src/common/description.cc:25]: This is still problematic. It is still causing build failures in the autopkgtest job, and will also break compilation on Clang, as it always sets the `__GNUG__` macro to `4`.

    $ clang++ -x c++ /dev/null -dM -E | grep GNUG
    #define __GNUG__ 4

You could try doing what I suggested in https://github.com/pistacheio/pistache/commit/e0c3f0f840dea155d67439385aed6613a1d54736#r79759584

```suggestion
#if __has_include(<filesystem>)
#include <filesystem>
namespace fs = std::filesystem;
#elif __has_include(<experimental/filesystem>)
#include <experimental/filesystem>
namespace fs = std::experimental::filesystem;
#endif
```

File: tests/rest_swagger_server_test.cc [hunk 2]
```diff
@@ -13,7 +13,13 @@
...
+#if ___GNUG__ <= 7
+#include <experimental/filesystem>
+namespace filesystem = std::experimental::filesystem;
+#else
 #include <filesystem>
+namespace filesystem = std::filesystem;
+#endif
 #include <httplib.h>
 
 using namespace std;
```
Comment (Tachi107) [inline tests/rest_swagger_server_test.cc:25]: Same as above, but note that here you rename `std::filesystem` to `filesystem`, and then `using namespace std;` is used, causing namespace clashes. Please change `namespace filesystem = ...` to `namespace fs = ...`, and then update the test code (and possibly run tests locally to make sure you don't break anything :)

**Review by Tachi107 — CHANGES_REQUESTED** [review]
The GCC 7 workaround is still broken, see my comments below

File: tests/rest_swagger_server_test.cc (hunk 2 above)
Comment (zydxhs) [reply tests/rest_swagger_server_test.cc:25]: I test clang 6.0/10.0 with gcc 7.5.0, it works fine.
Can you tell me your compilation environment?

**Comment by kiplingw** [comment]
> How to change debian/changelog ?

See the [debian](https://github.com/pistacheio/pistache/tree/debian) branch.

**Comment by zydxhs** [comment]
@kiplingw I find thd debian/changelog, bug I don't know what to change. I need an example

```
pistache (0.0.003-1) UNRELEASED; urgency=low

  * Initial release. Closes: #929593

 -- Kip Warner <kip@thevertigo.com>  Wed, 20 Oct 2021 18:33:00 +0000
```

**Comment by Tachi107** [comment]
Don't worry, I'll change it myself when this will get merged.

-- 
OpenPGP key: 66DE F152 8299 0C21 99EF  A801 A8A1 28A8 AB1C EE49

**Comment by zydxhs** [comment]
@Tachi107 Ok, it's good.

About "std::filesystem", I do the test at behind:

program:
```
#include <iostream>

#if __GNUG__ <= 7
#include <experimental/filesystem>
namespace fs = std::experimental::filesystem;
#else
#include <filesystem>
namespace fs = std::filesystem;
#endif

int main(){
    fs::create_directory("sandbox");
}
```
I using thd command behind, all is ok. I can't repeat your question, what did I do wrang ?
On ubuntu 18.04, clang 6.0/10.0 with gcc 7.5.0:
```
g++ -std=c++17 -ofs main.cpp -lstdc++fs
clang++ -std=c++17 -ofs main.cpp -lstdc++fs
clang++10 -std=c++17 -ofs main.cpp -lstdc++fs
```
And on On ubuntu 20.04, clang 10.0 with gcc 9.4.0:
```
g++ -std=c++17 -ofs main.cpp -lstdc++fs
clang++ -std=c++17 -ofs main.cpp -lstdc++fs
```

**Comment by Tachi107** [comment]
The issue is that you end up using experimental::filesystem on 
compilers that do not require it.

Let's take your example and call it gnug.cpp

    #if __GNUG__ <= 7
    #include <experimental/filesystem>
    #pragma message "Using experimental::filesystem"
    namespace fs = std::experimental::filesystem;
    #else
    #pragma message "Using std::filesystem"
    #include <filesystem>
    namespace fs = std::filesystem;
    #endif

    int main() {
        fs::create_directory("sandbox");
    }

Let's compile it with a recent clang version and see what happens

    $ clang++-14 -std=c++17 gnug.cpp
    gnug.cpp:3:9: warning: Using experimental::filesystem 
[-W#pragma-messages]
    #pragma message "Using experimental::filesystem"
            ^
    1 warning generated.
    /usr/bin/ld: /tmp/gnug-8c8ff3.o: in function `main':
    gnug.cpp:(.text+0x21): undefined reference to 
`std::experimental::filesystem::v1::create_directory(std::experimental::filesystem::v1::__cxx11::path 
const&)'
    /usr/bin/ld: /tmp/gnug-8c8ff3.o: in function 
`std::experimental::filesystem::v1::__cxx11::path::path<char [8], 
std::experimental::filesystem::v1::__cxx11::path>(char const (&) [8])':
    
gnug.cpp:(.text._ZNSt12experimental10filesystem2v17__cxx114pathC2IA8_cS3_EERKT_[_ZNSt12experimental10filesystem2v17__cxx114pathC2IA8_cS3_EERKT_]+0x55): 
undefined reference to 
`std::experimental::filesystem::v1::__cxx11::path::_M_split_cmpts()'
    clang: error: linker command failed with exit code 1 (use -v to see 
invocation)

The linking phase fails, because -lstdc++fs is required to use the old, 
non-standard experimental::filesystem.

Now, see what happens when using __has_include(); let's use this 
has_include.cpp file as an example:

    #if __has_include(<filesystem>)
    #pragma message "Using std::filesystem"
    #include <filesystem>
    namespace fs = std::filesystem;
    #elif __has_include(<experimental/filesystem>)
    #pragma message "Using experimental::filesystem"
    #include <experimental/filesystem>
    namespace fs = std::experimental::filesystem;
    #endif

    int main() {
        fs::create_directory("sandbox");
    }

And compile it with the same command line as before:

    $ clang++-14 -std=c++17 has_include.cpp
    has_include.cpp:2:9: warning: Using std::filesystem 
[-W#pragma-messages]
    #pragma message "Using std::filesystem"
            ^
    1 warning generated.

Everything works as expected, and the correct std::filesystem 
implementation is used.

Hope I've convinced you now :)

-- 
OpenPGP key: 66DE F152 8299 0C21 99EF  A801 A8A1 28A8 AB1C EE49

**Comment by zydxhs** [comment]
On ubuntu 18.04, clang compiled with gcc7, so "-lstdc++fs" and experimental/filesystem is needed.
On ubuntu 20.04, clang compiled with gcc9, so "-lstdc++fs" and experimental/filesystem is ***not*** needed.

I don't know how to resolved it.

**Comment by Tachi107** [comment]
> On ubuntu 18.04, clang compiled with gcc7, so clang 6.0 ~ 10.0 find gcc7's header, \"-lstdc++fs\" is needed.\nOn ubuntu 20.04, clang compiled with gcc9, so clang 6.0 ~ 12.0 find gcc9's header, \"-lstdc++fs\" is not needed.

This is already handled by our build system

https://github.com/pistacheio/pistache/blob/4c54e8f345b407cecd43a2a33fd44e888bc1c7f8/meson.build#L85-L94

**Comment by zydxhs** [comment]
```
#include <iostream>

#if __clang__
  #if __has_include(<filesystem>)
    #include <filesystem>
    namespace fs = std::filesystem;
    #pragma message "using clang std::filesystem"
  #else
    #include <experimental/filesystem>
    namespace fs = std::experimental::filesystem;
    #pragma message "using clang std::experimental::filesystem"
  #endif
#elif __GNUG__ <= 7
  #include <experimental/filesystem>
  namespace fs = std::experimental::filesystem;
  #pragma message "using g++ std::experimental::filesystem"
#else
  #include <filesystem>
  namespace fs = std::filesystem;
  #pragma message "using g++ std::filesystem"
#endif

int main(){
    fs::create_directory("sandbox");
}
```
On ubuntu 18.04, `clang++ -std=c++17 main.cpp -lstdc++fs` is ok, all clang version need -lstdc++fs.
On ubuntu 18.04, `clang++ -std=c++17 main.cpp` is ok, all clang version no need -lstdc++fs.

**Comment by kiplingw** [comment]
> @kiplingw I find thd debian/changelog, bug I don't know what to change. I need an example
> 
> ```
> pistache (0.0.003-1) UNRELEASED; urgency=low
> 
>   * Initial release. Closes: #929593
> 
>  -- Kip Warner <kip@thevertigo.com>  Wed, 20 Oct 2021 18:33:00 +0000
> ```

Bump the 003 to 004.

**Comment by zydxhs** [comment]
@Tachi107 @kiplingw That should be all right now.

On ubuntu18.04, I test with gcc 7.5.0 and clang 6.0
On ubuntu 20.04, I test with gcc 9.4 and clang 10.0
All the tests passed

**Comment by Tachi107** [comment]
Why was this merged like this? The commit history is extremely messy, and I'm not happy with the experimental::filesystem workaround. This may fix things for clang, but not for other GCC-compatible compilers, like ICC

**Comment by kiplingw** [comment]
Reverted. I'll stay out of your lane @Tachi107. All CI passes. When he's cleaned up what you'd like, I'll leave it to you to handle / merge.

**Comment by Tachi107** [comment]
@zydxhs is there a reason why you've used a lot of `ifdef`s instead of unconditionally using `__has_include()`?

Anyway, please re-submit this pull request again so that it can be merged for good

**Comment by zydxhs** [comment]
@Tachi107 Sorry. My intention was to be compatible with C++ compilers without `__has_include()`,  but I forgot that pistache need c++17.

I'll do it soon.
